#!/bin/bash
gcloud dns managed-zones list --project %project_name% | grep -v DESCRIP | awk '{print $1}' | while read pr; do gcloud dns record-sets list --zone=$pr --filter TYPE=A --project %project_name% ; done
echo "END script"
